import "../styles/globals.css";
import Link from "next/link";
export const metadata = {
  title: "My App",
  description: "Generated by Next.js",
};
export default function RootLayout({ children }) {
  return (
    <html lang="id">
      <body>{children}</body>
    </html>
  );
}
